### ISSUE TITLE
Link to current messages linking to an older commit

### ISSUE THREAD

**Issue by l92s** [xnt/react-something-nice#23]
In the read me could this be linked to the master messages.js file instead of a previous commit to ensure it is up to date, as it's only showing the messages initially committed? Happy to look at this :)

**Comment by izulien** [comment]
You have a good point @sianlouisa.  I updated a few links in my PR.  Both the Contribution and the messages listing should be relative to the project.  These changes should make it nicer for forked projects to have a relative link instead of a hard link.  I left the Issues link to the main project as ideally those issues could be corrected for all projects and get more traction here at the master.
